language: rust
rust:
  - stable
  - beta
  - 1.51.0

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

jobs:
  include:
    - os: linux
      rust: nightly
      before_install: curl -L https://github.com/mozilla/grcov/releases/download/v0.8.6/grcov-v0.8.6-x86_64-unknown-linux-gnu.tar.gz | tar zxf -
      script:
        - export CARGO_INCREMENTAL=0
        - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
        - export RUSTDOCFLAGS="-Cpanic=abort"
        - cargo build --all --verbose $CARGO_OPTIONS
        - cargo test --all --verbose $CARGO_OPTIONS
        - |
          zip -0 ccov.zip `find . \( -name "netcdf3*.gc*" \) -print`;
          ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
          bash <(curl -s https://codecov.io/bash) -f lcov.info;
  allow_failures:
    - rust: nightly
