name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.51.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - name: Install grcov
        run:  curl -L https://github.com/mozilla/grcov/releases/download/v0.8.6/grcov-v0.8.6-x86_64-unknown-linux-gnu.tar.gz | tar zxf -
      - name: Build
        run: cargo build --verbose
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'
      - name: Run tests
        run: cargo test --verbose
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'
      - name: Run grcov
        run: zip -0 ccov.zip `find . \( -name "netcdf3*.gc*" \) -print`;
            ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
            bash <(curl -s https://codecov.io/bash) -f lcov.info;
          
    # bench:
    #   name: Bench
    #   runs-on: ubuntu-latest

    #   - name: Install rust
    #     uses: actions-rs/toolchain@v1
    #     with:
    #       toolchain: nightly
    #       profile: minimal
    #       override: true

    #   - name: Compile bench
    #     uses: actions-rs/cargo@v1
    #     with:
    #       command: bench
    #       args: --verbose --no-run

    #   - name: Run bench
    #     uses: actions-rs/cargo@v1
    #     with:
    #       command: bench
    #       args: --verbose


